inventory/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name='index'),
    path('issuing/', views.IssueProduct.as_view(), name='issue-products'),
    path('receiving/', views.ReceiveProduct.as_view(), name='receive-products'),
    path('transact_api/', views.transact_api, name='transact-api'),
    path('transactions/', views.TransactionList.as_view(), name='transactions'),
    path('values/', views.InventoryList.as_view(), name='inventory-list'),

    path('products/', views.ProductList.as_view(), name='product-list'),
    path('products/add', views.ProductCreate.as_view(), name='product-add'),
    path('products/<int:pk>/', views.ProductUpdate.as_view(), name='product-update'),
    path('products/<int:pk>/delete', views.ProductDelete.as_view(), name='product-delete'),

    path('partners/', views.PartnerList.as_view(), name='partner-list'),
    path('partners/add', views.PartnerCreate.as_view(), name='partner-add'),
    path('partners/<int:pk>/', views.PartnerUpdate.as_view(), name='partner-update'),
    path('partners/<int:pk>/delete', views.PartnerDelete.as_view(), name='partner-delete'),
    
]

smepos/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserList.as_view(), name='user-list'),
    path('', views.UserList.as_view(), name='user-list'),
    path('add', views.UserCreate.as_view(), name='user-add'),
    path('<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    path('<int:pk>/delete', views.UserDelete.as_view(), name='user-delete'),

]

inventory/models.py
from django.db import models
from django.core.validators import MinValueValidator
from users.models import CustomUser as User

# Create your models here.

class Partner(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Partner name",)
    phone_number = models.CharField(max_length=100, unique=True, blank=True, null=True,)
    mobile_number = models.CharField(max_length=100, unique=True, blank=True, null=True,)
    address = models.CharField(max_length=100, blank=True, null=True,)
    email = models.EmailField(max_length=100, unique=True, blank=True, null=True,)
    is_vendor = models.BooleanField(default=False,)
    is_customer = models.BooleanField(default=False,)
    photo = models.ImageField(upload_to='avatars/partners', null=True, blank=True)
    responsible = models.ForeignKey(User, on_delete=models.PROTECT,)
    date = models.DateTimeField()

   
class Product(models.Model):
    name = models.CharField(max_length=200, unique=True, db_index=True, verbose_name="Product name",)
    description = models.CharField(max_length=200, db_index=True, blank=True, help_text="Optional information about the product",)
    code = models.CharField(max_length=50, unique=True, db_index=True, blank=True, null=True,)
    quantity = models.PositiveIntegerField()
    cost = models.DecimalField(decimal_places=2, max_digits=11, default=0.00, validators=[MinValueValidator(0.00)])
    price = models.DecimalField(decimal_places=2, max_digits=11, default=0.00, validators=[MinValueValidator(0.00)])
    photo = models.ImageField(upload_to='avatars/products', null=True, blank=True)
    responsible = models.ForeignKey(User, on_delete=models.PROTECT,)
    date = models.DateTimeField()
 

class Transaction(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT,)
    reference = models.CharField(max_length=200)
    trade_qty = models.IntegerField(default=0)
    unit_price = models.FloatField(default=0.00, validators=[MinValueValidator(0.00)])
    partner = models.ForeignKey(Partner, on_delete=models.PROTECT,)
    responsible = models.ForeignKey(User, on_delete=models.PROTECT,)
    date = models.DateTimeField()

inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.db.models import Sum ,Max , F, FloatField
from django.db import transaction
from django.http import HttpResponse
from django import forms

from search_listview.list import SearchableListView
from .models import Partner, Product, Transaction

def index(request):
    return HttpResponse("You will see all products here")


class Product_(PermissionRequiredMixin):
    model = Product
    permission_required = ('inventory.add_product')
    fields = ['photo', 'name', 'description', 'code', 'quantity',
                'cost', 'price',]
    success_url = reverse_lazy('inventory:product-list')


class ProductList(Product_, generic.ListView):
    context_object_name = 'product_list'
    permission_required = ('inventory.view_product')
    template_name = 'inventory/product_list.html'


class ProductCreate(Product_, generic.CreateView):
    
    def form_valid(self, form):
        form.instance.responsible = self.request.user
        form.instance.date = timezone.now()
        return super().form_valid(form)


class ProductUpdate(Product_, generic.UpdateView):
    pass


class ProductDelete(Product_, generic.DeleteView):
    pass


class Partner_(PermissionRequiredMixin,):
    model = Partner
    permission_required = ('inventory.add_partner')
    fields = ['photo', 'name', 'phone_number', 'mobile_number',
                'address', 'email', 'is_vendor', 'is_customer',]
    success_url = reverse_lazy('inventory:partner-list')
    
    
class PartnerList(Partner_, generic.ListView):
    context_object_name = 'partner_list'
    permission_required = ('inventory.view_partner')
    template_name = 'inventory/partner_list.html'


class PartnerCreate(Partner_, generic.CreateView):
    
    def form_valid(self, form):
        form.instance.responsible = self.request.user
        form.instance.date = timezone.now()

        return super().form_valid(form)


class PartnerUpdate(Partner_, generic.UpdateView):
    pass


class PartnerDelete(Partner_, generic.DeleteView):
    pass


#class TransactionList(generic.ListView):
class TransactionList(SearchableListView):
    model = Transaction
    template_name = "inventory/transaction_list.html"
    paginate_by = 10
    searchable_fields = ["product__name", "partner__name", "reference"]
    specifications = {
        "product__name": "__icontains",
        "partner__name": "__icontains",
        "reference": "__icontains",
        }
    
    def get_context_data(self, **kwargs):
        '''
        Convertion of the default query set to dictionary,
        is the most efficient way, known to me for now, I could get the
        selected items properties which will be used to populate the form
        '''
        transaction_list = Transaction.objects.annotate(total=Sum(F('trade_qty')*F('unit_price')))
        context = super(TransactionList, self).get_context_data(**kwargs)
        context['transaction_list'] = transaction_list
        print({"context":context})
        return context
    
    '''model = Transaction
    context_object_name = 'transaction_list'
    #permission_required = ('inventory.view_transaction')
    template_name = 'inventory/transaction_list.html'
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = self.model.objects.filter(name__icontains=query)
        else:
            object_list = self.model.objects.all()
        return object_list
    '''


class InventoryList(Partner_, generic.ListView):
    context_object_name = 'product_list'
    template_name = 'inventory/inventory_list.html'


class IssueProduct(PermissionRequiredMixin, generic.ListView):
    model = Product
    permission_required = ('inventory.add_product')
    fields = ['photo', 'name', 'code', 'quantity', 'price',]
    context_object_name = 'products'
    template_name = 'inventory/transact_base.html'

    
    def get_context_data(self, **kwargs):
        '''
        Convertion of the default query set to dictionary,
        is the most efficient way, known to me for now, I could get the
        selected items properties which will be used to populate the form
        '''
        trigger = "issuing"
        customers = Partner.objects.filter(is_customer=1)
        context = super(IssueProduct, self).get_context_data(**kwargs)
        context['other_params'] = {"partners":customers, "trigger":trigger}
        print({"context":context})
        return context

    def post(self, request):
        print("Thank you")

class ReceiveProduct(IssueProduct):

    def get_context_data(self, **kwargs):
        '''
        Convertion of the default query set to dictionary,
        is the most efficient way, known to me for now, I could get the
        selected items properties which will be used to populate the form
        '''
        trigger = "receiving"
        vendors = Partner.objects.filter(is_vendor=1)
        context = super(ReceiveProduct, self).get_context_data(**kwargs)
        context['other_params'] = {"partners":vendors, "trigger":trigger}
        print({"context":context})
        return context
    
@require_POST
def transact_api(request):
    ''' It is expected that the validation handling must have handle by
    the javascripts thus validation may not be neccessary here.'''
    # getting the result data
    trigger = partner = request.POST.get('trigger')
    prod_id_list = request.POST.getlist('prod_id_list[]')
    trade_qty_list=request.POST.getlist('trade_qty_list[]')
    unit_price_list=request.POST.getlist('unit_price_list[]')
    partner = Partner.objects.get(pk=request.POST.get('partner'))
    # computing the reference number
    if trigger=="receiving":
        ref_ = "IN"
    if trigger=="issuing":
        ref_ = "OUT"
    reference = ref_ + str(Transaction.objects.aggregate(id_max=Max('id'))['id_max']+1)
    # instantiate the new transaction list for later creation in bulk
    new_transact = [Transaction(
                        product=Product.objects.get(pk=prod_id_list[i]),
                        trade_qty=trade_qty_list[i],
                        unit_price=unit_price_list[i], 
                        partner=partner, 
                        reference=reference, 
                        responsible= request.user, 
                        date=timezone.now(),
                        ) for i in range(len(prod_id_list))]
    # select and lock the concerned product untill end of transaction
    prod_update = Product.objects.select_for_update().filter(pk__in=prod_id_list)
    #print(prod_update)
    with transaction.atomic():
        # Atomicity guarantees that an case an error is encountred
        # all pending transactions are rolled back
        Transaction.objects.bulk_create(new_transact)
        for i in range(len(prod_id_list)):
            if trigger=="receiving":
                prod_update.filter(pk=prod_id_list[i]).update(
                    quantity=F('quantity')+trade_qty_list[i])
            if trigger=="issuing":
                prod_update.filter(pk=prod_id_list[i]).update(
                    quantity=F('quantity')-trade_qty_list[i])
    return HttpResponse('Successful')

templates/inventory/alerts.html
<!-- successful validation-->
<div id="validate-success-alert" class="alert alert-success alert-dismissible fade show d-none" role="alert">
    <strong>Successfully validated!</strong>Ref__ 
    <button type="button" class="btn btn-success btn-sm ml-2">Print Receipt</button>
    <button type="button" class="close" onclick="$('#validate-success').addClass('d-none');">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

<!-- failed validation-->
<div id="validate-fail-alert" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
    <strong>Not validated!</strong> Please go through the form to remove invalid lines
    <button type="button" class="close" onclick="$('#validate-fail-alert').addClass('d-none');">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

<!-- invalid partner or product -->
<div id="empty-partner-product-alert" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
    <strong>Invalid data </strong> Please select a partner and product(s)
    <button type="button" class="close" onclick="$('#empty-partner-product-alert').addClass('d-none');">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

templates/inventory/inventory_list.html
{% extends 'base.html' %}

{% block main_page_area %}
<h3 class="page-header">Inventory Items List</h3>
<table id="myTable" class="table table-striped table-bordered table-responsive">

    <thead>
        <tr>
            <th>SKU</th>
            <th>Name</th>
            <th>Quantity</th>
        </tr>
    </thead>

    {% for product in product_list %}
        <tr>
            <td>{{ product.code|default_if_none:"--" }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.quantity }}</td>
        </tr>
    {% endfor %}

</table>
{% endblock main_page_area %}

templates/inventory/partner_form.html
{% extends 'base.html' %}

{% block main_page_area %}
<h3 class="page-header">Add a Partner</h3>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock main_page_area %}

templates/inventory/partner_list.html
{% extends 'base.html' %}

{% block main_page_area %}
<h3 class="page-header">Partners List</h3>
<table id="myTable" class="table table-striped table-bordered table-responsive">

    <thead>
        <tr>
            <th>Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Relationship</th>
        </tr>
    </thead>

    {% for partner in partner_list %}
        <tr>
            <td><a href="{% url 'inventory:partner-update' partner.id %}">{{ partner.name }}</a></td>
            <td>{{ partner.phone_number }}</td>
            <td>{{ partner.email }}</td>
            <td>
                {% if partner.is_vendor %}
                    <span class="badge badge-pill badge-light">Vendor</span>
                {% endif %} 
                {% if partner.is_customer %}
                    <span class="badge badge-pill badge-dark">Customer</span>
                {% endif %}
            </td>
        </tr>
    {% endfor %}

</table>
{% endblock main_page_area %}

templates/inventory/product_form.html
{% extends 'base.html' %}

{% block main_page_area %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock main_page_area %}

templates/inventory/product_list.html
{% extends 'base.html' %}

{% block main_page_area %}
<h3 class="page-header">Products List</h3>
<table id="myTable" class="table table-striped table-bordered table-responsive">

    <thead>
        <tr>
            <th>SKU</th>
            <th>Name</th>
            <th>Cost Price</th>
            <th>Sale Price</th>
        </tr>
    </thead>

    {% for product in product_list %}
        <tr>
            <td><a href="{% url 'inventory:product-update' product.id %}">{{ product.name }}</a></td>
            <td>{{ product.code|default_if_none:"--" }}</td>
            <td>{{ product.cost }}</td>
            <td>{{ product.price }}</td>
        </tr>
    {% endfor %}

</table>
{% endblock main_page_area %}

templates/inventory/transact_base.html
{% extends 'base.html' %}

{% block main_page_area %}
    <div class="row">
        <div class="col-12"><h2>{{other_params.trigger|capfirst}} Point</h2></div>
        <div class="col-md-3 pb-2">
            <p class="text-secondary">Partner name:</p>
        
            <select class='fstdropdown-select partner-select' id="inputGroupSelect01" data-placeholder="Start typing">
                <option value="">Select option</option>
                {% for item in other_params.partners %} <!--Type provided from backend-->
                <option value="{{item.id}}">{{ item.name }}</option>
                {% endfor %}
            </select>
        </div>
  
        
        <div class="col-9 col-md-7">    
            <span class="text-secondary">Input product details</span>

            <!-- The Alerts -->
            <div class="pt-3">
            {% include "inventory/alerts.html" %}
            </div>

            <form id="cart-form" class="form-group" onsubmit="rowAdder(); return false;">
                <div class="pb-3"> 
                    <select onchange="selectedData()" name='prod-select' class='fstdropdown-select' data-placeholder="Start typing">
                        <option value="">Select option</option>
                        {% for item in products %}
                        {{item}}
                            <option value="{{item.pk}}" prod_sku="{{item.code}}" prod_name="{{item.name}}" 
                                prod_max_qty="{{item.quantity}}" prod_std_price="{{item.price}}"
                                prod_photo="{{item.photo}}" prod_std_cost="{{item.cost}}">{{item.name}} [{{item.code}}]</option>
                        {% endfor %}
                    </select>
                </div>
                    <!--input type="text" class="form-control" placeholder="Enter Product" name="product_name_code"> </div-->
                <div class="row">
                    <div class="col-8">
                        <div class="form-inline">
                            <input type="number" class="form-control col-6" id="input_qty" placeholder="Qty" required="required">
                            <input type="number" step='0.01' class="form-control col-6" id="input_price" placeholder="Unit Price" required="required">
                        </div>
                    </div>
                    <button id="addRow" type="submit" class="btn btn-primary"><i class="fas fa-cart-plus"></i></button>
                </div>
            </form>
        </div>

        <div class="col-3 col-md-2">
        
            <img class="card image-responsive" style="height: 100px; width: auto;" src="download-2.jpg" alt="Card image cap">
        
        </div>
    </div>

    <form>
        <table id="myTable" class="display table table-striped table-bordered table-responsive">
            <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Qty</th>
                    <th>Unit Price</th>
                    <th>Amount</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>

            <!-- Area will be populated during issuing -->
            
            </tbody>
        </table>
    
    <br>

    <button class="btn btn-md btn-success" type="button" id="sales_validate">Validate</button>

    <button class="btn btn-danger" type="button" id="discard-cart">Discard</button>
    
    </form>


    <div class="dt-buttons"><button class="dt-button buttons-print" tabindex="0" aria-controls="myTable" type="button" onclick="printJS('myTable', 'html')"><span>Print</span></button> </div>


{% endblock main_page_area %}

{% block additional_bottom_styles_and_scripts %}
    {% load static %}
    <script>
        /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
        */
    $("#sales_validate").click(function () {
        
        var partner = $('.partner-select').val();

        /*
        Stop further execution if
            1. partner is not selected
            2. There is no row in the table body
        */
        if (partner=='' || $('#myTable tbody tr').length==0) {
            $("#empty-partner-product-alert").removeClass('d-none');
            return false; };

        console.log(partner);
        var prod_list=[]
        var trade_qty_list=[]
        var unit_price_list=[]

        $('#myTable tbody tr').each(function(){

            var prod_id = $(this).find("td:eq(1)").attr("id"); // get current row 2nd TD
            prod_list = prod_list.concat(prod_id);
            //console.log(prod_list);
            var trade_qty = $(this).find("td:eq(2)").text(); // get current row 3rd TD
            trade_qty_list=trade_qty_list.concat(trade_qty)
            //console.log(trade_qty_list);
            var unit_price=$(this).find("td:eq(3)").text(); // get current row 4th TD
            unit_price_list=unit_price_list.concat(unit_price)
            //console.log(unit_price_list);
            
        })
        //console.log(prod_list);
        //console.log(trade_qty_list);
        //console.log(unit_price_list);
        data = {
                'trigger': '{{other_params.trigger}}',
                'partner' : partner,
                'prod_id_list' : prod_list,
                'trade_qty_list' : trade_qty_list,
                'unit_price_list' : unit_price_list};
        console.log(data);
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            type: 'POST',
            url: "/inventory/transact_api/",
            data: data,
            dataType: 'json',
            success: function (response) {
                $("#validate-success-alert").removeClass('d-none');
            },
            error: function (response) {
                $("#validate-fail-alert").removeClass('d-none');
            }
        })

        return false; // Prevent reload
    
    });

    $("#discard-cart").click(function() {
        // Cart items are discarded by reloading the page
        location.reload(true);   
    });


    function selectedData() {
        // This function adds new row(s) to the table
        var input_qty = document.getElementById("input_qty");
        var input_price = document.getElementById("input_price");
        //var row = table.insertRow(-1);
        cart_form = document.forms["cart-form"];
        prod_obj = cart_form.elements["prod-select"]
            .options[cart_form.elements["prod-select"].selectedIndex];
        input_qty.value = "";
        
        if ('{{other_params.trigger}}'== 'issuing') {
            input_price.value = prod_obj.getAttribute("prod_std_price");
            input_qty.max = prod_obj.getAttribute("prod_max_qty");
            input_qty.placeholder = input_qty.max+" Available";
        } else {
            input_price.value = prod_obj.getAttribute("prod_std_cost");
        }
    }
    
    </script>
    <link rel="stylesheet" href="{% static 'fstdropdown/fstdropdown.css' %}">
    
    <script src="{% static 'js/transact_in.js' %}"></script>
    <script src="{% static 'js/print.min.css' %}"></script>
    <script src="{% static 'js/print.min.js' %}"></script>
    
    <script src="{% static 'fstdropdown/fstdropdown.js' %}"></script>
{% endblock additional_bottom_styles_and_scripts %}

templates/inventory/transact_in.html
{% extends 'base.html' %}

{% block main_page_area %}
    <div class="row">
        <div class="col-md-3 pb-2">
            <p class="text-secondary">Selling to:</p>
        
            <select class='fstdropdown-select partner-select' id="inputGroupSelect01" data-placeholder="Start typing">
                <option value="">Select option</option>
                {% for item in customers %}
                <option value="{{item.id}}">{{ item.name }}</option>
                {% endfor %}
            </select>
        </div>
  
        
        <div class="col-9 col-md-7">    
            <span class="text-secondary">Input product details</span>

            <!-- The Alerts -->
            <div class="pt-3">
            {% include "inventory/alerts.html" %}
            </div>

            <form id="cart-form" class="form-group" onsubmit="rowAdder(); return false;">
                <div class="pb-3"> 
                    <select onchange="selectedData()" name='prod-select' class='fstdropdown-select' data-placeholder="Start typing">
                        <option value="">Select option</option>
                        {% for item in products %}
                        {{item}}
                            <option value="{{item.pk}}" prod_sku="{{item.code}}" prod_name="{{item.name}}" 
                                prod_max_qty="{{item.quantity}}" prod_std_price="{{item.price}}"
                                prod_photo="{{item.photo}}">{{item.name}} [{{item.code}}]</option>
                        {% endfor %}
                    </select>
                </div>
                    <!--input type="text" class="form-control" placeholder="Enter Product" name="product_name_code"> </div-->
                <div class="row">
                    <div class="col-8">
                        <div class="form-inline">
                            <input type="number" class="form-control col-6" id="input_qty" placeholder="Qty" required="required">
                            <input type="number" step='0.01' class="form-control col-6" id="input_price" placeholder="Unit Price" required="required">
                        </div>
                    </div>
                    <button id="addRow" type="submit" class="btn btn-primary"><i class="fas fa-cart-plus"></i></button>
                </div>
            </form>
        </div>

        <div class="col-3 col-md-2">
        
            <img class="card image-responsive" style="height: 100px; width: auto;" src="download-2.jpg" alt="Card image cap">
        
        </div>
    </div>

    <form>
        <table id="myTable" class="display table table-striped table-bordered table-responsive">
            <thead>
                <tr>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Qty</th>
                    <th>Unit Price</th>
                    <th>Amount</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>

            <!-- Area will be populated during issuing -->
            
            </tbody>
        </table>
    
    <br>

    <button class="btn btn-md btn-success" type="button" id="sales_validate">Validate</button>

    <button class="btn btn-danger" type="button" id="discard-cart">Discard</button>
    
    </form>


    <div class="dt-buttons"><button class="dt-button buttons-print" tabindex="0" aria-controls="myTable" type="button" onclick="printJS('myTable', 'html')"><span>Print</span></button> </div>


{% endblock main_page_area %}

{% block additional_bottom_styles_and_scripts %}
    {% load static %}
    <script>
        /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
        */
    $("#sales_validate").click(function () {
        
        var partner = $('.partner-select').val();

        /*
        Stop further execution if
            1. partner is not selected
            2. There is no row in the table body
        */
        if (partner=='' || $('#myTable tbody tr').length==0) {
            $("#empty-partner-product-alert").removeClass('d-none');
            return false; };

        console.log(partner);
        var prod_list=[]
        var trade_qty_list=[]
        var unit_price_list=[]

        $('#myTable tbody tr').each(function(){

            var prod_id = $(this).find("td:eq(1)").attr("id"); // get current row 2nd TD
            prod_list = prod_list.concat(prod_id);
            //console.log(prod_list);
            var trade_qty = $(this).find("td:eq(2)").text(); // get current row 3rd TD
            trade_qty_list=trade_qty_list.concat(trade_qty)
            //console.log(trade_qty_list);
            var unit_price=$(this).find("td:eq(3)").text(); // get current row 4th TD
            unit_price_list=unit_price_list.concat(unit_price)
            //console.log(unit_price_list);
            
        })
        //console.log(prod_list);
        //console.log(trade_qty_list);
        //console.log(unit_price_list);
        data = {'partner' : partner,
                'prod_id_list' : prod_list,
                'trade_qty_list' : trade_qty_list,
                'unit_price_list' : unit_price_list};
        console.log(data);
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            type: 'POST',
            url: "/inventory/transact_api/",
            data: data,
            dataType: 'json',
            success: function (response) {
                $("#validate-success-alert").removeClass('d-none');
            },
            error: function (response) {
                $("#validate-fail-alert").removeClass('d-none');
            }
        })

        return false; // Prevent reload
    
    });

    $("#discard-cart").click(function() {
        // Cart items are discarded by reloading the page
        location.reload(true);   
    });
    
    </script>
    <link rel="stylesheet" href="{% static 'fstdropdown/fstdropdown.css' %}">
    
    <script src="{% static 'js/transact_in.js' %}"></script>
    <script src="{% static 'js/print.min.css' %}"></script>
    <script src="{% static 'js/print.min.js' %}"></script>
    
    <script src="{% static 'fstdropdown/fstdropdown.js' %}"></script>
{% endblock additional_bottom_styles_and_scripts %}

templates/inventory/transaction_list.html
{% extends 'base.html' %}

{% block main_page_area %}
<h3 class="page-header">Transaction Register</h3>

<div class="mb-2">
    {% include "search_listview/search_and_page.html" %}
</div>


<table id="myTable" class="table table-striped table-bordered table-responsive">

    <thead>
        <tr>
            <th>Date</th>
            <th>Reference</th>
            <th>Partner</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>By</th>
        </tr>
    </thead>

    {% for transaction in transaction_list %}
        <tr>
            <td>{{ transaction.date }}</td>
            <td>{{ transaction.reference }}</td>
            <td>{{ transaction.partner.name }}</td>
            <td>{{ transaction.product.name }}</td>
            <td>{{ transaction.trade_qty }}</td>
            <td>{{ transaction.unit_price }}</td>
            <td>{{ transaction.responsible.user_name }}</td>
        </tr>
    {% endfor %}

</table>

{% endblock main_page_area %}



{% block additional_bottom_styles_and_scripts %}
{% load static %}
    <script src="{% static 'search_listview/js/search_listview.js' %}"></script>
    <script>
        start_search()
    </script>
{% endblock additional_bottom_styles_and_scripts %}