inventory/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name='index'),
    path('issuing/', views.IssueProduct.as_view(), name='issue-products'),
    path('receiving/', views.ReceiveProduct.as_view(), name='receive-products'),
    path('transact_api/', views.transact_api, name='transact-api'),
    path('transactions/', views.TransactionList.as_view(), name='transactions'),
    path('values/', views.InventoryList.as_view(), name='inventory-list'),

    path('products/', views.ProductList.as_view(), name='product-list'),
    path('products/add', views.ProductCreate.as_view(), name='product-add'),
    path('products/<int:pk>/', views.ProductUpdate.as_view(), name='product-update'),
    path('products/<int:pk>/delete', views.ProductDelete.as_view(), name='product-delete'),

    path('partners/', views.PartnerList.as_view(), name='partner-list'),
    path('partners/add', views.PartnerCreate.as_view(), name='partner-add'),
    path('partners/<int:pk>/', views.PartnerUpdate.as_view(), name='partner-update'),
    path('partners/<int:pk>/delete', views.PartnerDelete.as_view(), name='partner-delete'),
    
]

smepos/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserList.as_view(), name='user-list'),
    path('', views.UserList.as_view(), name='user-list'),
    path('add', views.UserCreate.as_view(), name='user-add'),
    path('<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    path('<int:pk>/delete', views.UserDelete.as_view(), name='user-delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Inventory App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'bootstrap-4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-ui-1.12/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-5-13/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'sme-pos/css/main.css' %}">

</head>
<body>
    
    <!-- Top navigation bar -->
    <nav class='navbar fixed-top navbar-expand-md navbar-light bg-info'>
        <a class='navbar-brand' href='/'><strong style="color: white; font-size: 28px">
            Inventory App</strong>
        </a>
        <button class='navbar-toggler' type='button' data-toggle='collapse'
            data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent'
            aria-expanded='false' aria-label='Toggle navigation'>
            <span class='navbar-toggler-icon'></span>
        </button>

        <div class='collapse navbar-collapse justify-content-end' id='navbarSupportedContent'>
            <ul class='navbar-nav'>
                <li class='nav-item'>
                    <a class='nav-link' href='/'>About</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="/">Help</a>
                </li>

                {% if user.is_authenticated %}
                    <li class='nav-item'>
                        <a class='nav-link' href="{% url 'logout' %}">
                            Logout as {% if user.last_name %}{{user.last_name|title}}
                            {% else %} {{user.user_name|title}} {% endif %}
                        </a>
                    </li>
                {% else %}
                    <li class='nav-item'>
                        <a class='nav-link' href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}

                <li class='nav-item d-block d-md-none'>
                    <!-- Sidebar  -->
                    {% include 'sidebar.html' %}
                </li>
            </ul>

        </div>
    </nav>
    <!-- End of top navigation bar-->

    <!-- The main body -->
    <div class='container-fluid row pt-5'>
        <!-- Left Side bar -->
        <div class="col-12 col-md-2  bg-secondary bg-light d-none d-md-block sidebar-container">
            <div class="mt-5">
                <!-- Sidebar  -->
                {% include 'sidebar.html' %}
            </div>
        </div>
        <!-- End of Left Side bar -->
        
        <!-- Main page Area -->
        <div class="col-12 col-md-10 mt-5">
            {% block main_page_area %}
            {% endblock main_page_area %}
        </div>
    </div>

    <!-- Global scripts -->
    <script defer src="{% static 'bootstrap-4/js/popper.min.js' %}"></script>
    <script src="{% static 'jquery-ui-1.12/external/jquery/jquery.js' %}"></script>
    <script src="{% static 'bootstrap-4/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'sme-pos/js/csrf.js' %}"></script>
    <!-- End of global scripts -->

    {% block additional_bottom_styles_and_scripts %}
    <link rel="stylesheet" href="{% static 'datatables/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/buttons.datatables.min.css' %}">
    
    <script defer src="{% static 'datatables/jquery.datatables.min.js' %}"></script>
    <script defer src="{% static 'datatables/dataTables.buttons.min.js' %}"></script>
    <script defer src="{% static 'datatables/buttons.print.min.js' %}"></script>
    
    {% endblock additional_bottom_styles_and_scripts %}
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block main_page_area %}
{% if user.is_authenticated %}
    <p>Start Selling</p>
{% else %}
    <p> Kindly, <a href="{% url 'login' %}">Login</a></p>
{% endif %}

{% endblock %}

templates/sidebar.html
Quick Links
<ul class="list-group">
    <li class="list-group-item mt-2">
        <a href="{% url 'inventory:issue-products' %}"><i class="fas fa-shopping-cart mr-2"></i>Shop</a>
    </li>

    <li class="list-group-item mt-3">
        <a href="{% url 'inventory:product-list' %}"><i class="fas fa-cheese mr-2"></i>Product</a>
        <ul class="list-unstyled pl-4">
            <li><a href="{% url 'inventory:product-list' %}"><i class="fas fa-list mr-2"></i>List</a></lilist-inline-item">
            <li><a href="{% url 'inventory:product-add' %}"><i class="fas fa-plus mr-2"></i>New</a></li>
        </ul>
    </li>

    <li class="list-group-item mt-3">
        <a href="{% url 'inventory:inventory-list' %}"><i class="fas fa-warehouse mr-2"></i>Inventory</a>
        <ul class="list-unstyled pl-4">
            <li><a href="/"><i class="fas fa-truck-moving mr-2"></i>Receive</a></li>
            <li><a href="{% url 'inventory:inventory-list' %}"><i class="fas fa-coins mr-2"></i>Values</a></li>
            <li><a href="{% url 'inventory:transactions' %}"><i class="fas fa-exchange-alt mr-2"></i>Transactions</a></li>
        </ul>
    </li>

    <li class="list-group-item mt-3">
        <a href="{% url 'inventory:partner-list' %}"><i class="fas fa-handshake mr-2"></i>Partners</a>
        <ul class="list-unstyled pl-4">
            <li><a href="{% url 'inventory:partner-list' %}"><i class="fas fa-list mr-2"></i>List</a></li>
            <li><a href="{% url 'inventory:partner-add' %}"><i class="fas fa-plus mr-2"></i>New</a></li>
        </ul>
    </li>

    <li class="list-group-item mt-3">
        <a href="{% url 'users:user-list' %}"><i class="fas fa-users mr-2"></i>Users</a>
        <ul class="list-unstyled pl-4">
            <li><a href="{% url 'users:user-list' %}"><i class="fas fa-list mr-2"></i>List</a></li>
            <li><a href="/"><i class="fas fa-plus mr-2"></i>New</a></li>
        </ul>
    </li>
</ul>